- name: RHOAI
  product-listing-id: 63b85b573112fe5a95ee9a3a
  email-recipients:
    - openshift-ai-devtestops@redhat.com 
- name: RHBOAR
  product-listing-id: 66697a7154e5fd53fd1ebdd2
  email-recipients:
    - nipatil@redhat.com
    - pantinor@redhat.com
    - ewittman@redhat.com
    - rkubis@redhat.com
    - jsenko@redhat.com
    - carnalca@redhat.com
    - aperuffo@redhat.com
