name: Generate Image Health Report

on:
  schedule:
    - cron: '30 2 * * *'  # Runs at 9 AM IST (2:30 AM UTC)
  workflow_dispatch: {}

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'  # Specify the Python version you need

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies from Pipfile.lock
        run: pipenv install --ignore-pipfile

      - name: Generate Health Report
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: pipenv run python main.py

      - name: Extract HTML report from app.log
        run: |
          # Create the report.html file by extracting HTML content from app.log
          sed -n '/<html/,/<\/html>/p' app.log > report.html
        continue-on-error: true
      
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'report.html'

      - name: Print preview URL
        run: echo ${{ steps.html_preview.outputs.url }}

      - name: Upload logs and report as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            app.log
            report.html