name: Generate Image Health Report

on:
  schedule:
    - cron: '30 2 * * *'  # Runs at 9 AM IST (2:30 AM UTC)
  workflow_dispatch: {}

jobs:
  verify-nudges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'  # Specify the Python version you need

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies from Pipfile.lock
        run: pipenv install --ignore-pipfile

      - name: Generate Health Report
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: pipenv run python main.py

      - name: Upload debug logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.log
          path: app.log